workspace:
  base: /workspace
  path: sdgoogletagmanager

pipeline:
  setup:composer:
    image: docker.solutiondrive.de/library/composer:${PHP_VERSION}
    commands:
      - ./etc/scripts/prepareComposerJson.sh
      - composer update -n --no-progress --no-suggest
    volumes:
      - /var/cache/composer:/composer/cache
    secrets: [ composer_auth ]

  test:codingstandards:
    image: docker.solutiondrive.de/library/composer:${PHP_VERSION}
    commands:
      - ./etc/scripts/checkCodingStandards.sh
    when:
      matrix:
        PHP_VERSION: php7.2
        SHOPWARE_VERSION: 5.4.*

  test:spec:
    image: docker.solutiondrive.de/library/php-xdebug:${PHP_VERSION}
    commands:
      - vendor/bin/phpspec-standalone.${PHP_VERSION}.phar run --no-code-generation --format=dot

  test:unit:
    image: docker.solutiondrive.de/library/php-xdebug:${PHP_VERSION}
    commands:
      - vendor/bin/phpunit -c phpunit_unit.xml.dist

  publish:create:archive:
    image: docker.solutiondrive.de/library/composer:${PHP_VERSION}
    commands:
      - rm -rf /workspace/__release/sdGoogleTagManager*.zip
      - mkdir -p /workspace/__release/sdGoogleTagManager
      - git fetch
      - git archive ${DRONE_COMMIT_BRANCH} | tar -x -C /workspace/__release/sdGoogleTagManager
      - cd /workspace/__release/sdGoogleTagManager
      - composer install --no-dev -n -o --no-progress --no-suggest
      - cd /workspace/__release
      - zip -r sdGoogleTagManager.zip sdGoogleTagManager
      - rm -rf /workspace/__release/sdGoogleTagManager
    when:
      ref: [ refs/heads/master, refs/tags/* ]
      event: [push, tag]
      matrix:
        PHP_VERSION: php7.0
        SHOPWARE_VERSION: 5.2.*

  publish:create:master_archive:
    image: alpine:latest
    commands:
      - cp /workspace/__release/sdGoogleTagManager.zip /workspace/__release/sdGoogleTagManager-master.zip
    when:
      ref: [ refs/heads/master ]
      event: [push]
      matrix:
        PHP_VERSION: php7.0
        SHOPWARE_VERSION: 5.2.*

  publish:create:release_archive:
    image: alpine:latest
    commands:
      - cp /workspace/__release/sdGoogleTagManager.zip /workspace/__release/sdGoogleTagManager-${DRONE_COMMIT_BRANCH}.zip
    when:
      ref: [ refs/tags/* ]
      event: [tag]
      matrix:
        PHP_VERSION: php7.0
        SHOPWARE_VERSION: 5.2.*

  publish:create:latest_archive:
    image: alpine:latest
    commands:
      - cp /workspace/__release/sdGoogleTagManager.zip /workspace/__release/sdGoogleTagManager-latest.zip
    when:
      ref: [
        "refs/tags/v[0-9].[0-9].[0-9]",
        "refs/tags/v[0-9].[0-9].[0-9][0-9]",
        "refs/tags/v[0-9].[0-9][0-9].[0-9]",
        "refs/tags/v[0-9][0-9].[0-9].[0-9]",
        "refs/tags/v[0-9].[0-9][0-9].[0-9][0-9]",
        "refs/tags/v[0-9][0-9].[0-9].[0-9][0-9]",
        "refs/tags/v[0-9][0-9].[0-9][0-9].[0-9]",
        "refs/tags/v[0-9][0-9].[0-9][0-9].[0-9][0-9]"
        ]
      event: [tag]
      matrix:
        PHP_VERSION: php7.0
        SHOPWARE_VERSION: 5.2.*

  publish:s3:release:
    image: plugins/s3
    bucket: application-configs-385280725562
    region: eu-central-1
    acl: private
    source: /workspace/__release/sdGoogleTagManager-*.zip
    target: /releases/shopwareModules
    strip_prefix: /workspace/__release/
    when:
      ref: [ refs/heads/master, refs/tags/* ]
      event: [push, tag]
      matrix:
        PHP_VERSION: php7.0
        SHOPWARE_VERSION: 5.2.*


matrix:
  PHP_VERSION:
    - php7.2
    - php7.1
    - php7.0
  SHOPWARE_VERSION:
    - 5.4.*
    - 5.3.*
    - 5.2.*
