stages:
  - build
  - test

cache:
  key: "$CI_COMMIT_REF_SLUG$PHP_VERSION$SHOPWARE_VERSION"
  paths:
    - bin/.phpunit
    - vendor/
    - vendor-bin/
    - .env

.composer:
  stage: build
  image: solutiondrive/php-composer:${PHP_VERSION}
  script:
    - ./etc/scripts/prepareComposerJson.sh
    - composer install -n --no-progress
  tags:
    - memory_hungry

.phpspec:
  stage: test
  image: solutiondrive/php-xdebug:${PHP_VERSION}
  script:
    - vendor/bin/phpspec-standalone.${PHP_VERSION}.phar run --no-code-generation --format=dot

# START ONLY ON LATEST PHP VERSION
.codingstandards:
  stage: test
  image: solutiondrive/php-composer:${PHP_VERSION}
  script:
    - ./etc/scripts/checkCodingStandards.sh

.check_structure:
  stage: test
  image: alpine:latest
  script:
    - ./etc/scripts/checkForCorrectPluginStructure.sh
# END ONLY ON LATEST PHP VERSION

# TODO: Add publish pipeline

# START MATRIX DEFINITION
composer:php72_shopware56:
  variables:
    PHP_VERSION: php7.2
    SHOPWARE_VERSION: \~5.6.4
  extends: .composer

phpspec:php72_shopware56:
  variables:
    PHP_VERSION: php7.2
    SHOPWARE_VERSION: \~5.6.4
  extends: .phpspec

composer:php73_shopware56:
  variables:
    PHP_VERSION: php7.3
    SHOPWARE_VERSION: \~5.6.4
  extends: .composer

phpspec:php73_shopware56:
  variables:
    PHP_VERSION: php7.3
    SHOPWARE_VERSION: \~5.6.4
  extends: .phpspec

codingstandards:php73_shopware56:
  variables:
    PHP_VERSION: php7.3
    SHOPWARE_VERSION: \~5.6.4
  extends: .codingstandards

# END MATRIX DEFINITION
